### ISSUE TITLE
Lib directory not found

### ISSUE THREAD

**Issue by Almaz-KG** [vladimirvivien/clamshell-cli#16]
Hi everibody!

Please, help me!
I try to use this library but when I typing (java -jar cli.jar) I get a error message "Lib directory not found. ClamShell-Cli will exist"

How to resolve this problem?

Thansk

**Comment by vladimirvivien** [comment]
@Almaz-KG apologies for the late reply.  Hope you figured it out.  If not, please make sure lib directory is on the same directory as the cli.jar.

**Comment by Almaz-KG** [comment]
It was my mistake, so I am sorry :-)

**Comment by vladimirvivien** [comment]
@Almaz-KG No need to be sorry, thanks for using the tool! :+1:
